---
- hosts: all
  vars_prompt:
      - name: root_pwd
        prompt: "root password"
        private: yes
        encrypt: "sha512_crypt"
        confirm: yes

      - name: user_pwd
        prompt: "user password"
        private: yes
        encrypt: "sha512_crypt"
        confirm: yes
  roles:
     - system

- hosts: all
  become_user: "{{ username }}"
  become: yes
  roles:
      - user
      - deploy_config

#- hosts: all
  #tasks:
      #- name: CLEANUP | Remove root dotfiles folder
        #file: path=/root/dotfiles
              #state=absent
