---
- name: Get zsh path
  shell: cat /etc/shells | grep zsh | head -n 1
  register: zsh_path

- name: Change default shell
  become: yes
  become_user: root
  shell: chsh -s {{ zsh_path.stdout }} {{ item }}
  with_items:
      - "{{ username }}"
      - root
