---
- include: yaourt.yml
  when: ansible_os_family == "Archlinux"

- name: Update repos
  shell: yaourt -Syyu --noconfirm

- name: Install packages
  shell: yaourt -S {{ item }} --noconfirm --needed
  when: ansible_os_family == "Archlinux"
  ignore_errors: True
  with_items:
    # Xorg
    - xorg-server
    - xf86-video-fbdev
    - xorg-xinit
    - xclip
    - xautolock
    - numlockx

    # Utilies
    - ntp
    - alsa-utils
    - sysstat
    - acpi
    - cronie
    - libnotify
    - dunst
    - xorg-xrandr
    - arandr
    - termite
    #- redshift
    - udiskie

    # Dev utils
    - python-pip
    - zsh
    - vim
    - tmux
    - tmuxp
    - ack

    # Latex
    #- texlive-most

    # Web and network
    - openssl
    - curl
    - wget
    - chromium
    - transmission-cli

    # Desktop environment
    - i3
    - i3lock
    - i3blocks
    - rofi
    - unclutter
    - bc
    #- compton

    # Theming
    - feh
    - scrot
    - imagemagick
    - otf-inconsolata-powerline-git
    - ttf-impallari-cabin-font
    - ttf-font-awesome
    - terminus-font
    - ephifonts-no-helvetica
    - lxappearance
    - arc-icon-theme-git
    - arc-gtk-theme

    # File tools
    - nautilus
    #- nautilus-dropbox
    #- evince
    #- unzip
    #- git
    #- subversion

    # Multimedia
    #- vlc
    - kodi-rbp

- include: chsh.yml

- name: Change sudoers file
  become: yes
  become_user: root
  lineinfile: dest=/etc/sudoers
              regexp="%wheel ALL=(ALL) NOPASSWD:ALL"
             line="%wheel ALL=(ALL) ALL"
