---
- include: yaourt.yml
  when: ansible_os_family == "Archlinux"

- name: Update repos
  shell: yaourt -Syyu --noconfirm

- name: Install packages
  shell: yaourt -S {{ item }} --noconfirm --needed
  when: ansible_os_family == "Archlinux"
  ignore_errors: True
  with_items:
    # Xorg
    - xorg-server
    #- xorg-server-utils
    - xf86-video-fbdev
    - xorg-xinit
    - xclip
    - xautolock
    - numlockx

    # Utilies
    - ntp
    #- xf86-input-synaptics
    - alsa-utils
    - networkmanager
    - network-manager-applet
    - sysstat
    - acpi
    - cronie
    - libnotify
    - dunst
    - xorg-xrandr
    - arandr
    - termite
    #- redshift
    - udiskie

    # Dev utils
    - python-pip
    - zsh
    - vim
    - tmux
    - tmuxp
    - ack

    # Latex
    #- texlive-most

    # Web and network
    - openssl
    - curl
    - wget
    - chromium
    #- transmission-gtk

    # Desktop environment
    - i3
    - i3lock
    - i3blocks
    - rofi
    - unclutter
    - bc
    #- compton

    # Theming
    - feh
    - scrot
    - imagemagick
    - otf-inconsolata-powerline-git
    - ttf-impallari-cabin-font
    - ttf-font-awesome
    - terminus-font
    - ephifonts-no-helvetica
    - lxappearance
    - arc-icon-theme-git
    - arc-gtk-theme

    # File tools
    - nautilus
    #- nautilus-dropbox
    #- evince
    #- unzip
    #- git
    #- subversion

    # Multimedia
    #- vlc
    - kodi-rbp

#- name: Install virtualbox guest packages
  #shell: yaourt -S {{ item }} --noconfirm --needed
  #when: ansible_os_family == "Archlinux", virtualmachine == True
  #ignore_errors: True
  #with_items:
    #- virtualbox-guest-modules-arch
    #- virtualbox-guest-utils

#- name: Enable services
  #service: name={{ item }}
           #enabled=yes
  #become: yes
  #become_user: root
  #with_items:
      #- NetworkManager
      #- ntp
      #- cronie

#- name: Setup Cron jobs
  #become: yes
  #become_user: root
  #cron: name="Wallpaper"
        #state=present
        #minute="*/15"
        #job="DISPLAY=:0.0 /home/{{ username }}/scripts/random_wallpaper.sh"
        #user="{{ username }}"

#- include: git.yml

- include: chsh.yml

- name: Change sudoers file
  become: yes
  become_user: root
  lineinfile: dest=/etc/sudoers
              regexp="%wheel ALL=(ALL) NOPASSWD:ALL"
             line="%wheel ALL=(ALL) ALL"
