---
- name: Set boot options
  lineinfile: path=/boot/config.txt
              line="{{item}}"
  with_items:
    - "dtparam=audio=on"
    - "hdmi_drive=2"
    - "hdmi_group=1"
    - "hdmi_mode=16"
    - "disable_overscan=1"
