---
- name: Install grub and os-prober packages
  pacman: name=grub,os-prober state=present
  when: bootloader == "grub"

- name: Install Grub
  shell: grub-install {{ primary_disk }}
  when: bootloader == "grub"

- name: Make grub config
  shell: grub-mkconfig -o /boot/grub/grub.cfg
  when: bootloader == "grub"

#- name: Install uefibootmgr
  #pacman: name=uefibootmgr
          #state=present
  #when: bootloader == "uefi"

- name: Check boot manager status
  shell: cat /boot/loader/loader.conf
  register: bootctl_status
  ignore_errors: True

- name: Install boot manager
  shell: bootctl --path=/boot install
  when: bootloader == "uefi" and bootctl_status|failed

- name: Update boot manager
  shell: bootctl update
  when: bootloader == "uefi" and bootctl_status|succeeded

- name: Create loader conf
  copy: src=~/dotfiles/files/boot/loader.conf
        dest=/boot/loader/loader.conf
  when: bootloader == "uefi"

- name: Get boot partition PARTUUID
  shell: blkid -s PARTUUID -o value {{ root_partition }}
  register: root_partuuid
  when: bootloader == "uefi"

- name: Create loader entry
  template: src=~/dotfiles/files/boot/arch.conf
            dest=/boot/loader/entries/arch.conf
  when: bootloader == "uefi" and btrfs == False

- name: Create loader entry (btrfs)
  template: src=~/dotfiles/files/boot/arch_btrfs.conf
            dest=/boot/loader/entries/arch.conf
  when: bootloader == "uefi" and btrfs == True

