# KODI account setup
#####################

- name: Create kodi user account
  user: name=kodi
        password=kodi
        state=present

- name: Add kodi to wheel group
  user: name=kodi
        groups=wheel
        append=yes
        shell=/bin/zsh

- name: Link zprofile to kodi user conf
  copy: src=files/.zprofile
        dest=/home/kodi/.zprofile
        owner=kodi
        group=kodi

- name: Link xinitrc to kodi user conf
  copy: src=files/.xinitrc.kodi
        dest=/home/kodi/.xinitrc
        owner=kodi
        group=kodi

- name: Link zsh config for kodi user
  copy: src=files/{{ item }}
        dest=/home/kodi/{{ item  }} 
        owner=kodi
        group=kodi
  with_items:
    - .zshrc
    - .zprofile

- name: Add users to video group
  user: name={{item}}
        append=yes
        groups=video
  with_items:
      - "{{ username }}"
      - kodi
