---
- name: Install script dependencies
  pacman: name={{item}}
          state=present
  with_items:
      - base-devel

- name: Setup hostname
  shell: echo {{ hostname }} > /etc/hostname

- include: locale.yml

- name: Setup vconsole.conf
  template: src=vconsole.conf.j2
            dest=/etc/vconsole.conf

- name: Change fstab mount options (noatime)
  replace:  dest=/etc/fstab
            regexp='relatime'
            replace='noatime'
            backup=yes

- name: Set persistent mount point for MAXELL HDD 
  mount:    path=/mnt/maxellhdd
            src='LABEL=MAXELLHDD'
            state=mounted
            fstype=vfat

- name: Change boot config
  copy: src=files/bootconfig.txt
        dest=/boot/config.txt

- include: network.yml
- include: users.yml
- include: kodi.yml
