---
- name: Setup hostname
  shell: echo {{ hostname }} > /etc/hostname

- include: locale.yml

- name: Setup vconsole.conf
  template: src=vconsole.conf.j2
            dest=/etc/vconsole.conf

- name: Setup ramdisk
  shell: mkinitcpio -p linux

- name: Change fstab mount options (noatime)
  replace:  dest=/etc/fstab
            regexp='relatime'
            replace='noatime'
            backup=yes

#- include: bootloader.yml

- include: users.yml

#- name: Enable dhcpcd service
  #service: name=dhcpcd
           #enabled=yes
