#!/bin/bash

CPU_WARNING_THRESHOLD=50
CPU_CRITICAL_THRESHOLD=80

idle=`mpstat 1 1 | tr ' ' '\n' | tail -n 1`
cpu_load=`echo "100 - $idle" | bc -l`

case $BLOCK_BUTTON in
  1) termite --name __float__ -e top
esac

echo "$cpu_load%"
echo "$cpu_load%"

if [ `echo "$cpu_load > $CPU_CRITICAL_THRESHOLD" | bc -l` -eq 1 ]
then
    echo "#FF0000"
    exit 33
elif [ `echo "$cpu_load > $CPU_WARNING_THRESHOLD" | bc -l`  -eq 1 ]
then
    echo "#FFEA00"
    exit 0
fi
