---
- include: zsh.yml
- include: vim.yml
- include: tmux.yml
- include: scripts.yml
- include: dunst.yml
- include: i3.yml
- include: xfiles.yml
- include: termite.yml
  when: ansible_os_family == "Archlinux"

- include: yaourt.yml
  when: ansible_os_family == "Archlinux"

- include: root.yml
